base_url = "https://dawranliou.com"
title = "Daw-Ran Liou"
description = "Daw-Ran Liou's homepage"
compile_sass = true
generate_feed = true
taxonomies = [{name = "tags", feed = true}]
# build_search_index = true

[markdown]
highlight_code = false

[extra]
# Put all your custom variables here
